# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a804b8e1462dff7dbac4437d57d9786caf3e5da67b4ff0a9da829101c196b679b3c43be63651e9456e7e9c48aa7daf35b0fa098518a5d050b39d90f0af64a6e

test:
  secret_key_base: 61b88935d977a98fcbdebbe2cfef22e2b29d43ff4f1028edf51691e1f07015f6693c911c1fa6eef2c75a2fc47167284565b9aba810230fa2d09eb12fce6d5b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
